const data = {
    products: [
        {
            _id: '1',
            name: 'Pink Chiffon Flowing Dress',
            category: 'Dresses',
            image: '/images/p1.jpg',
            price: 120,
            brand: 'Anthropologie',
            rating: 4.5,
            numreviews: 10,
            description: 'comfortable',
        },
        {
            _id: '2',
            name: 'Yellow Mini Dress Dress',
            category: 'Dresses',
            image: '/images/p2.jpg',
            price: 150,
            brand: 'Dress Heaven',
            rating: 8,
            numreviews: 10,
            description: 'classy',
        },
        {
            _id: '3',
            name: 'Polkadot Midi Dress',
            category: 'Dresses',
            image: '/images/p3.jpg',
            price: 220,
            brand: 'Anthropologie',
            rating: 10,
            numreviews: 10,
            description: 'stylish',
        },
        {
            _id: '4',
            name: 'Belted Cotton Dress ',
            category: 'Dresses',
            image: '/images/p4.jpg',
            price: 125,
            brand: 'Anthropologie',
            rating: 1,
            numreviews: 10,
            description: 'flirty',
        },
        {
            _id: '5',
            name: 'Cotton Tshirt Dress',
            category: 'Dresses',
            image: '/images/p5.jpg',
            price: 120,
            brand: 'Dress Heaven',
            rating: 7.5,
            numreviews: 10,
            description: 'casual',
        },
        {
            _id: '6',
            name: 'Spaghetti Strap Dress',
            category: 'Dresses',
            image: '/images/p6.jpg',
            price: 175,
            brand: 'Old Navy',
            rating: 9.5,
            numreviews: 10,
            description: 'everyday',
        },
    ],
};

export default data;